language: python
python:
  - "2.7"
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=lint
  - TOXENV=coverage
install:
  - "pip install virtualenv tox"
script: tox
branches:
  only:
    - master
notifications:
  email: false